name: Build and Publish event-log-service
on:
  push:
    branches:
      - master
      - 'release-*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - '**.md'
  repository_dispatch:
    types: ['bahmni-embedded-tomcat-trigger']

jobs:
  build:
    name: Build event-log-service war
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Package war
        run: mvn clean install -U -DskipTests
      - uses: actions/upload-artifact@v3
        with:
          name: event-log-service.war
          path: event-log-service-webapp/target/event-log-service-webapp.war

  rpm-build-publish:
    name: RPM Build and Publish
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - name: Set artifact version
        run: |
          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
          ./setArtifactVersion.sh
          rm setArtifactVersion.sh
      - name: Download bahmni-embedded-tomcat.zip
        run: sh .github/download_artifact.sh bahmni-package bahmni-embedded-tomcat ${{secrets.BAHMNI_PAT}}
      - uses: actions/download-artifact@v3
        with:
          name: event-log-service.war
          path: package/rpm/resources/
      - name: Setup Java 8 for Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'      
      - name: Gradle Build
        run: |
            cd package/rpm
            export version=$(awk -F- '{print $1}' <<< ${{env.ARTIFACT_VERSION}})
            export release=$(awk -F- '{print $2}' <<< ${{env.ARTIFACT_VERSION}})
            ./gradlew -Pversion=$version -Prelease=$release clean buildRpm
      - uses: actions/upload-artifact@v3
        with:
          name: bahmni-event-log-service-rpm
          path: package/rpm/build/distributions/*.rpm